# -*- coding: utf-8 -*-
"""AssociationRules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYUd5OwTz3F3clkiYe0ZS9ezIAG9qh8u
"""

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules # Corrected the typo in the function name
from mlxtend.preprocessing import TransactionEncoder
# conda install -c conda-forge mlxtend

from google.colab import drive
drive.mount('/content/drive')

file_name ="/content/Titanic.csv"

titanic = pd.read_csv(file_name)
titanic

df=pd.get_dummies(titanic)
df.head()

frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True) # Changed 'min_supported' to 'min_support'
frequent_itemsets

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules

rules[rules.lift>1]

