# -*- coding: utf-8 -*-
"""drag_quantity_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LuUYatxp4Db3Ipi0649KPWdAOYgd2It-
"""

import pandas as pd
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import numpy as np

df = pd.read_csv('/content/patient_drag_quantity_data_with_30_features.csv')
df.to_csv(csv_file, index=False)

print(df)
label_encoder = LabelEncoder()
categorical_cols = ['Gender', 'Region', 'Grade Level', 'Mother Education', 'Father Education']
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

