# -*- coding: utf-8 -*-
"""DBSCANipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpkPwgFxrSjkTCppSmJBu4oZBUbN8uJs
"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/Wholesalecustomersdata.csv')

import pandas as pd
file_path="/content/Wholesale customers data.csv"
df=pd.read_csv(file_path)
df

df.drop(['Channel','Region'],axis=1,inplace=True)
array=df.values

array=df.values

array

stscaler = StandardScaler().fit(array)
X = stscaler.transform(array)

X

dbscan = DBSCAN(eps=0.8, min_samples=6)
dbscan.fit(X)

#Nosly samples are given the label -1.
dbscan.labels_

cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

cl

pd.concat([df,cl],axis=1)

