# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyacT2LLLEHllLy-1CMmiDvRPL1Lrkv1
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

from google.colab import drive
drive.mount('/content/drive')

file_name='/content/iris.csv'

import pandas as pd
iris=pd.read_csv(file_name)

iris

iris.head()

label_encoder=preprocessing.LabelEncoder()
iris['species']=label_encoder.fit_transform(iris['Species'])
iris['Species']

iris=pd.read_csv('iris.csv',index_col=0)

iris.head()

iris=iris.rename(columns={"species":"Flowers_types"})

iris

label_encoder=preprocessing.LabelEncoder()
iris['Species']=label_encoder.fit_transform(iris['Species'])
iris['Species']

x=iris.iloc[:,0:4]
y=iris['Species']

x

y

colnames=list(iris.columns)
colnames

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

model=DecisionTreeClassifier(criterion='entropy',max_depth=3)
model.fit(x_train,y_train)

tree.plot_tree(model);

