# -*- coding: utf-8 -*-
"""FeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VISHsUFOXhVMg9x1ejou635fN4puhqjj
"""

from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'masss', 'pedi', 'age', 'class']

dataframe = read_csv(filename, names=names)
print(dataframe)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
test = SelectKBest(score_func=chi2, k=4)
fit  = test.fit(X, Y)
print(names)
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)

from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
model = LogisticRegression(max_iter=400)
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X, Y)

fit.n_features_

fit.support_

fit.ranking_

from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
filename = '/content/pima-indians-diabetes.data.csv'
names =  ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
print(names)
dataframes = read_csv(filename, names=names)
array  = dataframe.values
X = array[:,0:8]
Y = array[:,8]
model =  DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

