# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAFtEDcWaET9UQVWxgnuj0YbUMD55mRr
"""

from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

import pandas as pd
df = pd.read_csv(file_name)

import seaborn as sns
sns.displot(df['daily'])

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(df['daily'], df['sunday'])
plt.xlabel('Daily')
plt.ylabel('Sunday')
plt.title('Scatter Plot of Daily vs. Sunday')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.regressionplots import influence_plot
import statsmodels.formula.api as snf
import numpy as np