# -*- coding: utf-8 -*-
"""Multi Linear Regresssion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXJCM57P3YH_i-goe6ZpA296USzI_Tiz
"""

from google.colab import files
uploaded = files.upload()
file_name=list(uploaded.keys())[0]
print(file_name)

df=pd.read_csv(file_name)
df

df.shape

df.corr(numeric_only=True)

#build model
import statsmodels.formula.api as smf


model=smf.ols('MPG~WT+VOL+SP+HP',data=df).fit()

model.params

print(model.tvalues, '\n', model.pvalues)

(model.rsquared, model.rsquared_adj)

ml_w=smf.ols('MPG~WT',data = df).fit()
print(ml_w.tvalues, '\n', ml_w.pvalues)

ml_w=smf.ols('MPG~WT+VOL',data = df).fit() # Changed 'cars' to 'df'
print(ml_w.tvalues, '\n', ml_w.pvalues)

