# -*- coding: utf-8 -*-
"""Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPS4WqZmy3BmP9bOEQ9CeBGhmi7hqYGJ
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
file_path = "/content/Movie.csv"
df = pd.read_csv(file_path)

movies_df = pd.read_csv('Movie.csv')

movies_df[0:5]

len(movies_df.userId.unique())

user_movies_df=movies_df.pivot(index='userId',columns='movie',values='rating').reset_index(drop=True)

user_movies_df

user_movies_df.index=movies_df.userId.unique()

user_movies_df

user_movies_df.fillna(0,inplace=True)

user_movies_df

from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

from scipy.spatial.distance import correlation
vec1=[5,4,0,0]
vec2=[4,5,3,0]
correlation_distance=correlation(vec1,vec2)
print(correlation_distance)

user_sim = 1 - pairwise_distances( user_movies_df.values,metric='cosine')

user_sim

user_sim_df = pd.DataFrame(user_sim)

