# -*- coding: utf-8 -*-
"""toyota.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uT7SMj2-nU23JCkWCVS-kTnzN1zTfha
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
print(file_name)
df = pd.read_excel(file_name)

df

df.shape

df.info()

df_new = df.drop(["Model","Fuel_Type"],axis=1)

df.corr

