# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_ncGYCXvW7aOQI2UcrXofBLW8ugT162
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

aaa = list(uploaded.keys())[0]

df=pd.read_csv(aaa)
df

df.iloc[1:3,2:4]

df.iloc[20:23,2:4]

df.iloc[[7,5,25,38],2:12:8]

df.describe()

df.loc[0:3]

df.head(10)
df.iloc[1:50,1:15]
data = df['First Name'] == 'Preston'
#company name as 'Vega-Gentry'
data

df.drop('Phone 2',axis =1)

df.isnull()

import pandas as pd
import numpy as np

dict1 ={'Customer_id':[2,4,6,7,8],'State':['California','California','Texas','New York','India']}
dict2 ={'Customer_id':[1,3,5,9,7],'State':['California','Australia','USA','Ireland','UK']}
df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)
df1,df2





"""# New Section"""

#inner_join_df = pd.merge(df1,df2,on = 'Customer_id',how = 'inner')
outer_join_df = pd.merge(df1,df2,on = 'Customer_id',how = 'outer')
outer_join_df
#inner_join_df

left_join =pd.merge(df1,df2,on='Customer_id',how ='left')
#right_join =pd.merge(df1,df2,on='Customer_id',how ='right')
left_join
#right_join